services:
  - type: web
    name: zain-media-admin
    runtime: python
    region: singapore
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn server:app --log-level debug
    envVars:
      - key: SMTP_EMAIL
        value: memogazar049@gmail.com
      - key: SECRET_KEY
        generateValue: true
